name: Setup Tools
description: Installs Terraform, Node.js, and dependencies for the workflow

runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Install Node.js for Lambda
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y zip