name: Deploy to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  bootstrap:
    name: Bootstrap Terraform State and IAM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials (Static)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Log Commit SHA
        run: |
          echo "Running on commit: ${GITHUB_SHA}"
          git log -1
      - name: Tear Down and Bootstrap Terraform State Bucket
        id: check-and-run
        run: |
          BUCKET_NAME="tfs-${{ secrets.AWS_ACCOUNT_ID }}"
          WEBSITE_BUCKET="${{ secrets.S3_BUCKET }}-${{ secrets.AWS_ACCOUNT_ID }}"
          
          if aws s3 ls "s3://$BUCKET_NAME" 2>/dev/null; then
            echo "State bucket $BUCKET_NAME already exists, skipping bootstrap"
            echo "ran=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "State bucket $BUCKET_NAME does not exist, running bootstrap..."
          echo "ran=true" >> $GITHUB_OUTPUT
          
          mkdir -p bootstrap
          cd bootstrap
          
          echo "Removing existing resources..."
          
          empty_and_delete_bucket() {
            local bucket=$1
            echo "Checking if $bucket exists..."
            if aws s3 ls "s3://$bucket" 2>/dev/null; then
              echo "Checking if $bucket has objects..."
              OBJECT_COUNT=$(aws s3api list-objects-v2 --bucket "$bucket" --query 'Contents | length(@)' --output text 2>/dev/null || echo 0)
              if [ "$OBJECT_COUNT" -gt 0 ]; then
                echo "$bucket has $OBJECT_COUNT objects, emptying it..."
                aws s3 rm "s3://$bucket" --recursive || { echo "Failed to empty $bucket"; exit 1; }
                ATTEMPTS=20
                DELAY=5
                for ((i=1; i<=$ATTEMPTS; i++)); do
                  OBJECT_COUNT=$(aws s3api list-objects-v2 --bucket "$bucket" --query 'Contents | length(@)' --output text 2>/dev/null || echo 0)
                  if [ "$OBJECT_COUNT" -gt 0 ]; then
                    echo "$bucket still has $OBJECT_COUNT objects, waiting $DELAY seconds (attempt $i/$ATTEMPTS)..."
                    sleep $DELAY
                  else
                    echo "$bucket is now empty"
                    break
                  fi
                done
                if [ $i -gt $ATTEMPTS ]; then
                  echo "Error: $bucket still has objects after $ATTEMPTS attempts"
                  exit 1
                fi
              else
                echo "$bucket is already empty"
              fi
              echo "Deleting $bucket..."
              aws s3 rb "s3://$bucket" --force || { echo "Failed to delete $bucket"; exit 1; }
            else
              echo "$bucket does not exist, skipping deletion"
            fi
            ATTEMPTS=20
            DELAY=5
            for ((i=1; i<=$ATTEMPTS; i++)); do
              if aws s3 ls "s3://$bucket" 2>/dev/null; then
                echo "$bucket still exists, waiting $DELAY seconds (attempt $i/$ATTEMPTS)..."
                sleep $DELAY
              else
                echo "$bucket successfully deleted"
                break
              fi
            done
            if [ $i -gt $ATTEMPTS ]; then
              echo "Error: $bucket still exists after $ATTEMPTS attempts"
              exit 1
            fi
          }
          
          empty_and_delete_bucket "$WEBSITE_BUCKET"
          
          echo "Detaching policies from GitHubActionsRole..."
          aws iam detach-role-policy --role-name GitHubActionsRole --policy-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/GitHubActionsPolicy" 2>/dev/null || echo "GitHubActionsPolicy not attached"
          aws iam detach-role-policy --role-name GitHubActionsRole --policy-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/GitHubS3UploadPolicy" 2>/dev/null || echo "GitHubS3UploadPolicy not attached"
          aws iam detach-role-policy --role-name GitHubActionsRole --policy-arn "arn:aws:iam::aws:policy/AdministratorAccess" 2>/dev/null || echo "AdministratorAccess not attached"
          
          echo "Deleting GitHubActionsRole..."
          aws iam delete-role --role-name GitHubActionsRole 2>/dev/null || echo "GitHubActionsRole not found or already deleted"
          
          echo "Deleting IAM policies..."
          aws iam delete-policy --policy-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/GitHubActionsPolicy" 2>/dev/null || echo "GitHubActionsPolicy not found"
          aws iam delete-policy --policy-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/GitHubS3UploadPolicy" 2>/dev/null || echo "GitHubS3UploadPolicy not found"
          
          echo "Deleting Lambda execution role..."
          aws iam detach-role-policy --role-name lambda-exec-role-${{ secrets.AWS_ACCOUNT_ID }} --policy-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/lambda-logs-${{ secrets.AWS_ACCOUNT_ID }}" 2>/dev/null || echo "Lambda logs policy not attached"
          aws iam delete-role --role-name lambda-exec-role-${{ secrets.AWS_ACCOUNT_ID }} 2>/dev/null || echo "lambda-exec-role-${{ secrets.AWS_ACCOUNT_ID }} not found or already deleted"
          aws iam delete-policy --policy-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/lambda-logs-${{ secrets.AWS_ACCOUNT_ID }}" 2>/dev/null || echo "lambda-logs-${{ secrets.AWS_ACCOUNT_ID }} policy not found"
          
          echo "Deleting lambda function..."
          aws lambda delete-function --function-name basic-auth-${{ secrets.AWS_ACCOUNT_ID }} || echo "Failed to delete basic-auth-${{ secrets.AWS_ACCOUNT_ID }}"
          echo "Waiting 10 seconds for Lambda deletion to propagate..."
          sleep 10
          echo "Deleting OIDC provider..."
          aws iam delete-open-id-connect-provider --open-id-connect-provider-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:oidc-provider/token.actions.githubusercontent.com" 2>/dev/null || echo "OIDC provider not found"
          
          cat <<EOF > bootstrap.tf
          provider "aws" {
            region = "${{ env.AWS_REGION }}"
          }
          data "aws_caller_identity" "current" {}
          module "tfstate_s3" {
            source     = "../modules/tfstate_s3"
            account_id = data.aws_caller_identity.current.account_id
          }
          module "github_actions_integration" {
            source      = "../modules/github_actions_integration"
            account_id  = data.aws_caller_identity.current.account_id
            github_repo = "${{ github.repository }}"
            bucket_arn  = module.tfstate_s3.bucket_arn
          }
          EOF
          
          rm -rf .terraform terraform.tfstate*
          terraform init -no-color || { echo "terraform init failed"; exit 1; }
          terraform apply -auto-approve -no-color || { echo "terraform apply failed"; exit 1; }
        env:
          TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

  apply:
    name: Terraform Apply and Deploy
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Node.js for Lambda
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Debug IAM Permissions
        run: |
          echo "Assumed Role Identity:"
          aws sts get-caller-identity
          echo "Listing Lambda Functions (test permissions):"
          aws lambda list-functions || echo "Failed to list Lambda functions"
      - name: Wait for IAM Propagation
        run: |
          echo "Waiting 30 seconds for IAM policy propagation..."
          sleep 30
      - name: Run Terraform
        run: |
          echo "Running apply job - v3 - timestamp: $(date +%s)"
          BUCKET_NAME="tfs-${{ secrets.AWS_ACCOUNT_ID }}"
          terraform init -no-color -backend-config="bucket=$BUCKET_NAME" -backend-config="key=state/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}" || { echo "terraform init failed"; exit 1; }
          terraform apply -auto-approve -no-color -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var="github_repo=${{ github.repository }}" -var="website_password=${{ secrets.WEBSITE_PASSWORD }}" -var="website_username=${{ secrets.WEBSITE_USERNAME }}"
        env:
          TF_LOG: DEBUG
      - name: Sync files to S3
        run: |
          aws s3 sync ./web/ s3://${{ secrets.S3_BUCKET }}-${{ secrets.AWS_ACCOUNT_ID }} --delete
      - name: Output Protected URL
        id: output-url
        run: |
          PROTECTED_URL=$(terraform output -raw protected_url)
          echo "Protected URL: $PROTECTED_URL"
          echo "protected_url=$PROTECTED_URL" >> $GITHUB_OUTPUT
      - name: Check CloudFront Distribution Exists
        id: check-cloudfront
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items[?Origins.Items[0].DomainName==`${{ secrets.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com`].Id' --output text 2>/dev/null)
          if [ -z "$DISTRIBUTION_ID" ] || [ "$DISTRIBUTION_ID" = "None" ]; then
            echo "No CloudFront distribution found for ${{ secrets.S3_BUCKET }}.s3.${{ env.AWS_REGION }}.amazonaws.com"
            echo "distribution_exists=false" >> $GITHUB_OUTPUT
          else
            echo "CloudFront distribution found: $DISTRIBUTION_ID"
            echo "CLOUDFRONT_DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV
            echo "distribution_exists=true" >> $GITHUB_OUTPUT
          fi
      - name: Invalidate CloudFront Cache
        if: steps.check-cloudfront.outputs.distribution_exists == 'true'
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"