name: Setup Environment

on:
  workflow_call:
    outputs:
      commit_sha:
        description: "The commit SHA of the current run"
        value: ${{ jobs.setup.outputs.commit_sha }}
      aws_region:
        description: "The AWS region for the workflow"
        value: ${{ jobs.setup.outputs.aws_region }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.log-sha.outputs.commit_sha }}
      aws_region: ${{ steps.set-region.outputs.aws_region }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Node.js for Lambda
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Log Commit SHA
        id: log-sha
        run: |
          echo "Running on commit: ${GITHUB_SHA}"
          git log -1
          echo "commit_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: Set AWS Region
        id: set-region
        run: |
          REGION="us-east-1"
          echo "Setting aws_region to: $REGION"
          echo "aws_region=$REGION" >> $GITHUB_OUTPUT
      - name: Debug Outputs
        run: |
          echo "commit_sha output: ${{ steps.log-sha.outputs.commit_sha }}"
          echo "aws_region output: ${{ steps.set-region.outputs.aws_region }}"