name: Setup Environment

on:
  workflow_call:
    outputs:
      commit_sha:
        description: "The commit SHA of the current run"
        value: ${{ jobs.setup.outputs.commit_sha }}
      aws_region:
        description: "The AWS region for the workflow"
        value: ${{ jobs.setup.outputs.aws_region }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.log-sha.outputs.commit_sha }}
      aws_region: ${{ steps.set-region.outputs.aws_region }}
    steps:
      - name: Setup Tools
        uses: ./.github/composite-actions/setup-tools
      - name: Log Commit SHA
        id: log-sha
        run: |
          echo "Running on commit: ${GITHUB_SHA}"
          git log -1
          echo "commit_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: Set AWS Region
        id: set-region
        run: |
          REGION="us-east-1"
          echo "Setting aws_region to: $REGION"
          echo "aws_region=$REGION" >> $GITHUB_OUTPUT